- name: Verify ssh_server_allowgroups is set correctly
  assert:
    that:
      - ssh_server_allowgroups is defined
      - ssh_server_allowgroups is iterable
    quiet: true

- name: Verify ssh_server_allowtcpforwarding is set correctly
  assert:
    that:
      - ssh_server_allowtcpforwarding is defined
      - ssh_server_allowtcpforwarding is boolean
    quiet: true

- name: Verify ssh_server_allowusers is set correctly
  assert:
    that:
      - ssh_server_allowusers is defined
      - ssh_server_allowusers is iterable
    quiet: true

- name: Verify ssh_server_banner is set correctly
  assert:
    that:
      - ssh_server_banner is defined
      - ssh_server_banner is string
    quiet: true

- name: Verify ssh_server_ciphers is set correctly
  assert:
    that:
      - ssh_server_ciphers is defined
      - ssh_server_ciphers is iterable
    quiet: true

- name: Verify ssh_server_clientalivecountmax is set correctly
  assert:
    that:
      - ssh_server_clientalivecountmax is defined
      - ssh_server_clientalivecountmax is integer
    quiet: true

- name: Verify ssh_server_clientaliveinterval is set correctly
  assert:
    that:
      - ssh_server_clientaliveinterval is defined
      - ssh_server_clientaliveinterval is integer
    quiet: true

- name: Verify ssh_server_denygroups is set correctly
  assert:
    that:
      - ssh_server_denygroups is defined
      - ssh_server_denygroups is iterable
    quiet: true

- name: Verify ssh_server_denyusers is set correctly
  assert:
    that:
      - ssh_server_denyusers is defined
      - ssh_server_denyusers is iterable
    quiet: true

- name: Verify ssh_server_hostbasedauthentication is set correctly
  assert:
    that:
      - ssh_server_hostbasedauthentication is defined
      - ssh_server_hostbasedauthentication is boolean
    quiet: true

- name: Verify ssh_server_ignorerhosts is set correctly
  assert:
    that:
      - ssh_server_ignorerhosts is defined
      - ssh_server_ignorerhosts is boolean
    quiet: true

- name: Verify ssh_server_kexalgorithms is set correctly
  assert:
    that:
      - ssh_server_kexalgorithms is defined
      - ssh_server_kexalgorithms is iterable
    quiet: true

- name: Verify ssh_server_logingracetime is set correctly
  assert:
    that:
      - ssh_server_logingracetime is defined
      - ssh_server_logingracetime is integer
    quiet: true

- name: Verify ssh_server_loglevel is set correctly
  assert:
    that:
      - ssh_server_loglevel is defined
      - ssh_server_loglevel|lower is in ["quiet", "fatal", "error", "info", "verbose", "debug", "debug1", "debug2", "debug3"]
    quiet: true

- name: Verify ssh_server_macs is set correctly
  assert:
    that:
      - ssh_server_macs is defined
      - ssh_server_macs is iterable
    quiet: true

- name: Verify ssh_server_maxauthtries is set correctly
  assert:
    that:
      - ssh_server_maxauthtries is defined
      - ssh_server_maxauthtries is integer
    quiet: true

- name: Verify ssh_server_maxsessions is set correctly
  assert:
    that:
      - ssh_server_maxsessions is defined
      - ssh_server_maxsessions is integer
    quiet: true

- name: Verify ssh_server_maxstartups is set correctly
  assert:
    that:
      - ssh_server_maxstartups is defined
      - ssh_server_maxstartups is string
    quiet: true

- name: Verify ssh_server_permitemptypasswords is set correctly
  assert:
    that:
      - ssh_server_permitemptypasswords is defined
      - ssh_server_permitemptypasswords is boolean
    quiet: true

- name: Verify ssh_server_permitrootlogin is set correctly
  assert:
    that:
      - ssh_server_permitrootlogin is defined
      - ssh_server_permitrootlogin is in [true, false, "without-password", "prohibit-password", "forced-commands-only"]
    quiet: true

- name: Verify ssh_server_permituserenvironment is set correctly
  assert:
    that:
      - ssh_server_permituserenvironment is defined
      - ssh_server_permituserenvironment is boolean
    quiet: true

- name: Verify ssh_server_usepam is set correctly
  assert:
    that:
      - ssh_server_usepam is defined
      - ssh_server_usepam is boolean
    quiet: true

- name: Verify ssh_server_x11forwarding is set correctly
  assert:
    that:
      - ssh_server_x11forwarding is defined
      - ssh_server_x11forwarding is boolean
    quiet: true
