- name: Verify role variables
  assert:
    that:
      - ssh_server_allowgroups is defined
      - ssh_server_allowgroups is iterable
      - ssh_server_allowtcpforwarding is defined
      - ssh_server_allowtcpforwarding is boolean
      - ssh_server_allowusers is defined
      - ssh_server_allowusers is iterable
      - ssh_server_banner is defined
      - ssh_server_banner is string
      - ssh_server_ciphers is defined
      - ssh_server_ciphers is iterable
      - ssh_server_clientalivecountmax is defined
      - ssh_server_clientalivecountmax is integer
      - ssh_server_clientaliveinterval is defined
      - ssh_server_clientaliveinterval is integer
      - ssh_server_denygroups is defined
      - ssh_server_denygroups is iterable
      - ssh_server_denyusers is defined
      - ssh_server_denyusers is iterable
      - ssh_server_hostbasedauthentication is defined
      - ssh_server_hostbasedauthentication is boolean
      - ssh_server_ignorerhosts is defined
      - ssh_server_ignorerhosts is boolean
      - ssh_server_kexalgorithms is defined
      - ssh_server_kexalgorithms is iterable
      - ssh_server_logingracetime is defined
      - ssh_server_logingracetime is integer
      - ssh_server_loglevel is defined
      - ssh_server_loglevel|lower is in ["quiet", "fatal", "error", "info", "verbose", "debug", "debug1", "debug2", "debug3"]
      - ssh_server_macs is defined
      - ssh_server_macs is iterable
      - ssh_server_maxauthtries is defined
      - ssh_server_maxauthtries is integer
      - ssh_server_maxsessions is defined
      - ssh_server_maxsessions is integer
      - ssh_server_maxstartups is defined
      - ssh_server_maxstartups is string
      - ssh_server_permitemptypasswords is defined
      - ssh_server_permitemptypasswords is boolean
      - ssh_server_permitrootlogin is defined
      - ssh_server_permitrootlogin is in [true, false, "without-password", "prohibit-password", "forced-commands-only"]
      - ssh_server_permituserenvironment is defined
      - ssh_server_permituserenvironment is boolean
      - ssh_server_usepam is defined
      - ssh_server_usepam is boolean
      - ssh_server_x11forwarding is defined
      - ssh_server_x11forwarding is boolean
    quiet: true
