# Set and validate role variables.
---
- name: Perform system validation
  assert:
    that: "ansible_os_family is in ['Debian']"
    fail_msg: "Unsupported OS family: {{ ansible_os_family }}"
    quiet: true

- name: Define ssh_server_package
  set_fact:
    ssh_server_package: "{{ __ssh_server_package }}"
  when: ssh_server_package is not defined
