---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-debian10-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-"/sbin/init"}
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
