---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if SSH is installed
      package:
        name: openssh-server
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

